name: ${project.artifactId}
main: com.mcmiddleearth.enforcersuite.EnforcerSuite
version: ${project.version}
website: ${project.url}
description: makes OBing a player easier
author: DonoA
authors: [DonoA, aaldim]
commands:
  punish:
    description: OathBreaker a player
    usage: |
            /punish <ob|ban> <player> <severity>
  done:
    description: finish your OB
    usage: |
            /done
  getinfo:
    description: Get info on a player
    usage: |
            /getinfo
  pardon:
    description: pardon a player from their sins
    usage: |
            /pardon <player>
    