name: ${project.artifactId}
main: com.mcmiddleearth.enforcersuite.EnforcerSuite
version: ${project.version}
website: ${project.url}
description: makes OBing a player easier
author: DonoA
authors: [DonoA, aaldim]
commands:
  ob:
    description: OathBreaker a player
    usage: |
            /ob <player name | UUID> <severity 1 | 2>
  ban:
    description: OathBreaker a player
    usage: |
            /ban <player name | UUID> <severity 1 | 2>
  done:
    description: finish your OB
    usage: |
            /done
  getinfo:
    description: Get info on a player
    usage: |
            /getinfo
  pardon:
    description: pardon a player from their sins
    usage: |
            /pardon <player>
  suitetool:
    description: Used for development (not for real use)
    usage: |
            /suitetool <command>
    