name: ${project.artifactId}
main: com.mcmiddleearth.enforcersuite.EnforcerSuite
version: ${project.version}
website: ${project.url}
description: makes OBing a player easier
author: DonoA
authors: [DonoA, aaldim]
commands:
  ob:
    description: OathBreaker a player
    usage: |
            /ob <player> <severity>
  done:
    description: finish your OB
    usage: |
            /done
    