name: enforcer Suite
main: com.mcmiddleearth.enforcersuite.enforcerSuite
version: 0.1
description: makes OBing a player easier
commands:
  ob:
    description: OathBreaker a player
    usage: |
            /ob <player> <severity>
  done:
    description: finish your OB
    usage: |
            /done
    